force-app/main/default/objects/Housing_user__c/Housing_user__c.object-meta.xml
<CustomObject>
    <label>Housing_user</label>
    <nameField>
        <label>Housing_user_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Housing_user__c/fields/Debet_Account__c.field-meta.xml
<CustomField>
    <fullName>Debet_Account__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Debet Account</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

devorg/force-app/main/default/classes/RemindHousingUserAboutDebtTest.cls
@isTest
private class RemindHousingUserAboutDebtTest
{
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    @isTest(SeeAllData=true)
    private static void testScheduledJob()
    {

        Housing_user__c[] cUser = [SELECT Id, Debet_Account__c, Email__c
                                   FROM Housing_user__c
                                   WHERE Email__c = 'dp090292pda@gmail.com'
                                   LIMIT 1];
        cUser[0].Debet_Account__c = -1000.00;
        update cUser;
        system.debug(cUser);
        Integer mails = Limits.getEmailInvocations();
        Test.startTest();
        // Schedule the test job
        String jobId = System.schedule('ScheduledApexTest',
                                       CRON_EXP,
                                       new RemindHousingUserAboutDebt());
        // Verify the scheduled job has not run yet.
        system.assert(mails == Limits.getEmailInvocations());
        Test.stopTest();

    }
}