force-app/main/default/objects/Housing_user__c/Housing_user__c.object-meta.xml
<CustomObject>
    <label>Housing_user</label>
    <nameField>
        <label>Housing_user_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devorg/force-app/main/default/objects/Housing_user__c/fields/Appartment__c.field-meta.xml
<CustomField>
    <fullName>Appartment__c</fullName>
    <label>Appartment</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last_name</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>User password for sign in.</description>
    <label>Password</label>
    <length>64</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HousingRegisterController.cls
global with sharing class HousingRegisterController
{
    private final String szErrDifferentPasswords = 'Different passwords inputted.';
    private final String szErrEmptyFields = 'All fields must be filled.';
    private final String szErrMaskStart = 'The error is occured:';
    private final String szErrAffectedFields = 'Affected fields';
    private final String szLoginPage = '/apex/Housing_login';
    private final Housing_user__c cUser;
    public HousingRegisterController(ApexPages.StandardController stdController)
    {
        this.cUser = (Housing_user__c)stdController.getRecord();
    }
    public String redirectToHousingLoginPage {get; set;}
    public String szUsername {get; set;}
    public String szEmail {get; set;}
    public String szFirstName {get; set;}
    public String szLastName {get; set;}
    public String szStreet {get; set;}
    public String szAppartment {get; set;}
    public String szPassword {get; set;}
    public String szConfirmPassword {get; set;}

    private boolean isValidPassword()
    {
        return szPassword == szConfirmPassword;
    }

    private Boolean isValidFields()
    {
        if(szUsername == null || szEmail == null || szPassword == null || szAppartment == null || szConfirmPassword == null ||
               szStreet == null || szFirstName == null || szLastName == null)
        {
            return false;
        }
        return true;
    }

    public PageReference registerUser()
    {
        if(!isValidPassword())
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, szErrDifferentPasswords));
            return null;
        }
        if(!isValidFields())
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, szErrEmptyFields));
            return null;
        }

        cUser.Name = szUsername.trim();
        cUser.Email__c = szEmail.trim();
        cUser.Password__c = szPassword.trim();
        cUser.Appartment__c = szAppartment.trim();
        cUser.Street__c = szStreet.trim();
        cUser.First_Name__c = szFirstName.trim();
        cUser.Last_name__c = szLastName.trim();

        Database.SaveResult dbResult = Database.insert(cUser, false);
        if(!dbResult.isSuccess())
        {
            for(Database.Error dbError : dbResult.getErrors())
            {
                System.debug(szErrMaskStart);
                System.debug(dbError.getStatusCode() + ': ' + dbError.getMessage());
                System.debug(szErrAffectedFields + dbError.getFields());
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,dbError.getMessage()));
            }
            return null;
        }
        return redirectToHousingLoginPage();
    }

    public PageReference redirectToHousingLoginPage()
    {
        PageReference prReference = new PageReference(szLoginPage);
        prReference.setRedirect(true);
        return prReference;
    }
}