force-app/main/default/objects/Housing_user__c/Housing_user__c.object-meta.xml
<CustomObject>
    <label>Housing_user</label>
    <nameField>
        <label>Housing_user_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devorg/force-app/main/default/objects/Housing_user__c/fields/Appartment__c.field-meta.xml
<CustomField>
    <fullName>Appartment__c</fullName>
    <label>Appartment</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Donetsk</fullName>
            </value>
            <value>
                <fullName>Lugansk</fullName>
            </value>
            <value>
                <fullName>Kharkov</fullName>
            </value>
            <value>
                <fullName>Kiev</fullName>
            </value>
            <value>
                <fullName>Rovno</fullName>
            </value>
            <value>
                <fullName>Chernigov</fullName>
            </value>
            <value>
                <fullName>Lvov</fullName>
            </value>
            <value>
                <fullName>Uzhgorod</fullName>
            </value>
            <value>
                <fullName>Ternopol</fullName>
            </value>
            <value>
                <fullName>Odessa</fullName>
            </value>
            <value>
                <fullName>Mariupol</fullName>
            </value>
            <value>
                <fullName>Kherson</fullName>
            </value>
            <value>
                <fullName>Dnepr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last_name</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>User password for sign in.</description>
    <label>Password</label>
    <length>64</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HousingUserWelcomeTest.cls
@isTest
private with sharing class HousingUserWelcomeTest
{
    @isTest
    private static void userWelcomeTest()
    {
        Housing_user__c cUser = new Housing_user__c(/*Username__c = 'test', Email__c = 'test@test.com',
                Password__c = 'test', Appartment__c = '2', City__c = 'Donetsk',*/
                Street__c = 'test, 2', /*Region__c = 'East',*/ First_Name__c = 'test',
                Last_name__c = 'test');
        insert cUser;
        System.assert(Limits.getEmailInvocations()==1);
    }

}