force-app/main/default/objects/Housing_user__c/Housing_user__c.object-meta.xml
<CustomObject>
    <label>Housing_user</label>
    <nameField>
        <label>Housing_user_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devorg/force-app/main/default/objects/Housing_user__c/fields/Appartment__c.field-meta.xml
<CustomField>
    <fullName>Appartment__c</fullName>
    <label>Appartment</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Donetsk</fullName>
            </value>
            <value>
                <fullName>Lugansk</fullName>
            </value>
            <value>
                <fullName>Kharkov</fullName>
            </value>
            <value>
                <fullName>Kiev</fullName>
            </value>
            <value>
                <fullName>Rovno</fullName>
            </value>
            <value>
                <fullName>Chernigov</fullName>
            </value>
            <value>
                <fullName>Lvov</fullName>
            </value>
            <value>
                <fullName>Uzhgorod</fullName>
            </value>
            <value>
                <fullName>Ternopol</fullName>
            </value>
            <value>
                <fullName>Odessa</fullName>
            </value>
            <value>
                <fullName>Mariupol</fullName>
            </value>
            <value>
                <fullName>Kherson</fullName>
            </value>
            <value>
                <fullName>Dnepr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Debet_Account__c.field-meta.xml
<CustomField>
    <fullName>Debet_Account__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Debet Account</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last_name</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HousingUserControllerTest.cls
@isTest
private with sharing class HousingUserControllerTest
{
    @testSetup
    private static void setup()
    {
        Housing_user__c hu = new Housing_user__c(Name = 'TestName',
                                                 Email__c = 'test@force.com',
                                                 Appartment__c = '1',
                                                 City__c = 'Donetsk',
                                                 Region__c = 'East',
                                                 Street__c = 'Str 1110',
                                                 First_Name__c = 'Name',
                                                 Last_Name__c = 'Last');
        insert hu;
    }
    @isTest
    private static void testPutNewMeterReadingsUser()
    {
        Housing_user__c cUser = [select Id from Housing_user__c where Name = 'TestName' limit 1];
        system.debug(cUser.Id);
        String szUserId = cUser.Id;
        HousingUserController cController = new HousingUserController();
        cController.cUser = cController.getHousingUser(szUserId);
        cController.getRates();
        cController.initMeterReadingValues();
        cController.szElectricity = '25';
        cController.szWater = '25';
        cController.szGas = '25';
        test.startTest();
        system.assertEquals(null, cController.putMeterReadingValues());
        test.stopTest();
    }
    @isTest
    private static void testGetPaymentHistoryUser()
    {
        Housing_user__c cUser = [select Id from Housing_user__c where Name = 'TestName' limit 1];
        system.debug(cUser.Id);
        String szUserId = cUser.Id;
        HousingUserController cController = new HousingUserController();
        cController.cUser = cController.getHousingUser(szUserId);
        cController.getRates();
        cController.szPayment = '20';
        cController.makePayment();
        List<HousingUserController.DisplayPaymentHistory> lHistory= cController.getPaymentHistory();
        test.startTest();
        system.assert(lHistory.size() > 0);
        system.assertNotEquals(0, lHistory.get(0).dDisplayAmount);
        system.assertNotEquals(null, lHistory.get(0).dtDisplayDateTime);
        test.stopTest();
    }
    @isTest
    private static void testChangeAdressUser()
    {

        Housing_user__c cUser = [select Id from Housing_user__c where Name = 'TestName' limit 1];
        system.debug(cUser.Id);
        String szUserId = cUser.Id;
        HousingUserController cController = new HousingUserController();
        cController.cUser = cController.getHousingUser(szUserId);
        cController.getRates();
        cController.szPayment = '20';
        cController.makePayment();
        test.startTest();
        system.assertEquals(null, cController.changeAddressStart());
        system.assertEquals(true, cController.bChangeAddressVisible);

        cController.cUser.Debet_Account__c = -1;

        system.assertEquals(null, cController.changeAddressStart());

        cController.szAppartment = '5';
        cController.szCity = 'Lugansk';
        cController.szRegion = 'East';
        cController.szStreet = 'Str Lenina, 20';

        system.assertEquals(null, cController.changeAddressFinish());
        test.stopTest();
    }
    @isTest
    private static void testMessagingUser()
    {
        Housing_user__c cUser = [select Id from Housing_user__c where Name = 'TestName' limit 1];
        system.debug(cUser.Id);
        String szUserId = cUser.Id;
        HousingUserController cController = new HousingUserController();
        cController.cUser = cController.getHousingUser(szUserId);
        cController.getRates();
        cController.sendEmailToManager();
        test.startTest();
        system.assertEquals(true, cController.bNewMessageVisible);

        test.stopTest();
    }
}