force-app/main/default/objects/Housing_user__c/Housing_user__c.object-meta.xml
<CustomObject>
    <label>Housing_user</label>
    <nameField>
        <label>Housing_user_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Housing_user__c/fields/Debet_Account__c.field-meta.xml
<CustomField>
    <fullName>Debet_Account__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Debet Account</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HousingInvoiceCalculationTest.cls
@isTest
private with sharing class HousingInvoiceCalculationTest
{
    @isTest(SeeAllData=true)
    private static void calculateDebtAmountTest()
    {
        /*Housing_user__c[] lUsers = [select Id, Email__c, Debet_Account__c, Region__c, Meter_reading_electricity__c,
                                           Meter_reading_gas__c, Meter_reading_water__c
                                    from Housing_user__c
                                    limit 1];

        system.assertNotEquals(null, HousingInvoiceCalculation.calculateDebtAmount(lUsers[0], 2.0, 2.0, 2.0, 2.0, 2.0, 2.0));*/
    }
    @isTest
    private static void calculateElectricityAmountTest()
    {
        system.assertEquals(4, HousingInvoiceCalculation.calculateElectricityAmount(2.0, 2.0));
    }
    @isTest
    private static void calculateWaterAmountTest()
    {
        system.assertEquals(4, HousingInvoiceCalculation.calculateWaterAmount(2.0, 2.0));
    }
    @isTest
    private static void calculateGasAmountTest()
    {
        system.assertEquals(4, HousingInvoiceCalculation.calculateGasAmount(2.0, 2.0));
    }
    @isTest
    private static void changeUserDebtAfterPaymentTest()
    {
        system.assertEquals(4, HousingInvoiceCalculation.changeUserDebtAfterPayment(2.0, 2.0));
    }
    @isTest(SeeAllData=true)
    private static void redactDebtAmountTest()
    {
        /*Housing_user__c cRedactUser = [SELECT Id, Email__c, Debet_Account__c, Meter_reading_electricity__c, Meter_reading_water__c, Meter_reading_gas__c
        FROM Housing_user__c
        LIMIT 1];
        HousingInvoiceCalculation.redactDebtAmount(cRedactUser, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0);*/
    }

}