devorg/force-app/main/default/objects/Fields_Analysis__c/Fields_Analysis__c.object-meta.xml
<CustomObject>
    <label>Fields Analysis</label>
    <nameField>
        <label>Fields Analysis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields Analysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fields_Analysis__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fields_Analysis__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fields_Analysis__c/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <label>Usage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/FieldsUsageCalculator.cls
global with sharing class FieldsUsageCalculator implements Database.Batchable<sObject>, Database.Stateful{
    private FieldAnalysisStructure requestInfo;
    private List<String> fields;
    private Map<String, Decimal> results = new Map<String, Decimal>();
    private Integer recordCount = 0;

    public FieldsUsageCalculator(FieldAnalysisStructure requestInfo) {
        this.requestInfo = requestInfo;
        try{
            this.fields = FieldService.getNonRequiredFields(requestInfo.objectName);
        }
        catch(Exception ex){
            this.requestInfo.errorMessage = 'Cannot get fields because: ' + ex.getMessage();
            this.requestInfo.isSuccess = false;            
            throw new FieldsUsageCalculatorException(this.requestInfo.errorMessage);
        }
        
        for(String fieldName : fields){
            results.put(fieldName, 0.0);
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT ' + String.join(this.fields,',') + ' FROM ' + this.requestInfo.objectName;
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<sObject> records){
        if(this.requestInfo.isSuccess){            
            for(sObject record : records){
                for(String fieldName : this.fields){
                    if(record.get(fieldName) != null){
                        results.put(fieldName, results.get(fieldName) + 1);
                    }
                }
                recordCount++;
            }                       
        }        
    }    

    global void finish(Database.BatchableContext bc){
        List<Fields_Analysis__c> historicalRecords = new List<Fields_Analysis__c>();
        
        for(String field : results.keySet()){            
            Decimal percentage = results.get(field)/recordCount * 100;            
            results.put(field, percentage.setScale(2));
            historicalRecords.add(new Fields_Analysis__c(Object_Name__c = this.requestInfo.objectName,
                                                        JobId__c = bc.getJobId(),
                                                        Field_Name__c = field,
                                                        Usage__c = percentage));
        }
        insert historicalRecords;        
        
        System.Queueable job = new FieldUsageInfoSender(requestInfo);
        System.enqueueJob(job);
        
    }    

    global class FieldsUsageCalculatorException extends Exception{}
}