devorg/force-app/main/default/objects/Housing_payment__c/Housing_payment__c.object-meta.xml
<CustomObject>
    <label>Housing_payment</label>
    <nameField>
        <label>Housing_payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devorg/force-app/main/default/objects/Housing_payment__c/fields/Housing_user__c.field-meta.xml
<CustomField>
    <fullName>Housing_user__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Housing_user</label>
    <referenceTo>Housing_user__c</referenceTo>
    <relationshipLabel>Housing_payments</relationshipLabel>
    <relationshipName>Housing_payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/Housing_user__c.object-meta.xml
<CustomObject>
    <label>Housing_user</label>
    <nameField>
        <label>Housing_user_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Housing_user__c/fields/Debet_Account__c.field-meta.xml
<CustomField>
    <fullName>Debet_Account__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Debet Account</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last_name</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

devorg/force-app/main/default/classes/RemindHousingUserAboutDebt.cls
global class RemindHousingUserAboutDebt implements Schedulable
{
  global void execute(SchedulableContext ctx)
    {
        List<Housing_user__c> lUsers = [SELECT Id, Email__c, First_Name__c, Last_name__c, Debet_Account__c, (select CreatedDate from Housing_payments__r) 
                                        FROM Housing_user__c
                                        WHERE Debet_Account__c < 0
                                        ORDER BY Debet_Account__c];
        system.debug(lUsers[0]);
        if(lUsers.size() > 0)
        {
            List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
            for(Housing_user__c item : lUsers)
            {
                system.debug(item);
                if(item.CreatedDate < (system.now()-30))
                {
                    String szBody = 'Hello, ' + item.First_Name__c + '! <br> ';
                    szBody += 'Please note that your balance is:';
                    szBody += '<br>';
                    szBody += item.Debet_Account__c;
                    szBody += '<br>';
                    szBody += 'Please pay it as soon as possible! <br>';
                    szBody += 'With kind regards.';
                    HousingMessager.sendMessage(szBody, 'Attention!', item.Email__c);
                }
            }
        }
        
    }

}