devorg/force-app/main/default/objects/Housing_invoice__c/Housing_invoice__c.object-meta.xml
<CustomObject>
    <label>Housing_invoice</label>
    <nameField>
        <label>Housing_invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devorg/force-app/main/default/objects/Housing_invoice__c/fields/Bill_amount__c.field-meta.xml
<CustomField>
    <fullName>Bill_amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bill amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_invoice__c/fields/Electricity_bill__c.field-meta.xml
<CustomField>
    <fullName>Electricity_bill__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Electricity bill</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_invoice__c/fields/Electricity_meter_reading__c.field-meta.xml
<CustomField>
    <fullName>Electricity_meter_reading__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Electricity_meter_reading</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Housing_invoice__c/fields/Gas_bill__c.field-meta.xml
<CustomField>
    <fullName>Gas_bill__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Gas bill</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_invoice__c/fields/Gas_meter_reading__c.field-meta.xml
<CustomField>
    <fullName>Gas_meter_reading__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Gas_meter_reading</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_invoice__c/fields/Housing_user__c.field-meta.xml
<CustomField>
    <fullName>Housing_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Housing_user</label>
    <referenceTo>Housing_user__c</referenceTo>
    <relationshipLabel>Housing_invoices</relationshipLabel>
    <relationshipName>Housing_invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Housing_invoice__c/fields/Water_bill__c.field-meta.xml
<CustomField>
    <fullName>Water_bill__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Water bill</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Housing_invoice__c/fields/Water_meter_reading__c.field-meta.xml
<CustomField>
    <fullName>Water_meter_reading__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Water_meter_reading</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Housing_rates__c/Housing_rates__c.object-meta.xml
<CustomObject>
    <label>Housing_rates</label>
    <nameField>
        <label>Housing_rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devorg/force-app/main/default/objects/Housing_rates__c/fields/Electricity_rate__c.field-meta.xml
<CustomField>
    <fullName>Electricity_rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Electricity_rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_rates__c/fields/Gas_rate__c.field-meta.xml
<CustomField>
    <fullName>Gas_rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Gas_rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_rates__c/fields/Water_rate__c.field-meta.xml
<CustomField>
    <fullName>Water_rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Water_rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/Housing_user__c.object-meta.xml
<CustomObject>
    <label>Housing_user</label>
    <nameField>
        <label>Housing_user_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Housing_user__c/fields/Debet_Account__c.field-meta.xml
<CustomField>
    <fullName>Debet_Account__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Debet Account</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

devorg/force-app/main/default/classes/HousingInvoiceCalculation.cls
public with sharing class HousingInvoiceCalculation
{
    public static Decimal calculateDebtAmount(Housing_user__c cUser,
                                              Decimal dElectricityMeterReading,
                                              Decimal dWaterMeterReading,
                                              Decimal dGasMeterReading,
                                              Decimal dElectricityRate,
                                              Decimal dWaterRate,
                                              Decimal dGasRate)
    {
        Decimal dDebtAmount = dElectricityMeterReading * dElectricityRate +
                              dWaterMeterReading * dWaterRate +
                              dGasMeterReading * dGasRate;
        cUser.Debet_Account__c = cUser.Debet_Account__c - dDebtAmount;
        update cUser;
        return cUser.Debet_Account__c;
    }

    public static Decimal calculateElectricityAmount(Decimal dElectricityMeterReading,
                                                     Decimal dElectricityRate)
    {
        return dElectricityMeterReading * dElectricityRate;
    }
    public static Decimal calculateWaterAmount(Decimal dWaterMeterReading, Decimal dWaterRate)
    {
        return dWaterMeterReading * dWaterRate;
    }
    public static Decimal calculateGasAmount(Decimal dGasMeterReading, Decimal dGasRate)
    {
        return dGasMeterReading * dGasRate;
    }
    public static Decimal changeUserDebtAfterPayment(Decimal dUserAcc, Decimal dPayment)
    {
        if(dPayment <= 0)
        {
            throw new HousingPaymentException();
        }
        return dUserAcc + dPayment;
    }
    public static void redactDebtAmount(Housing_rates__c cRates,
                                        Housing_invoice__c cInvoice,
                                        Decimal dElectricityMeterReading,
                                        Decimal dWaterMeterReading,
                                        Decimal dGasMeterReading)
    {
        Housing_user__c cUser = [select Id, Debet_Account__c from Housing_user__c where Id = :cInvoice.Housing_user__c limit 1];
        cUser.Debet_Account__c = cUser.Debet_Account__c + cInvoice.Bill_amount__c;
        update cUser;
        cInvoice.Bill_amount__c = calculateElectricityAmount(dElectricityMeterReading, cRates.Electricity_rate__c) +
                                  calculateWaterAmount(dWaterMeterReading, cRates.Water_rate__c) +
                                  calculateGasAmount(dGasMeterReading, cRates.Gas_rate__c);
        cInvoice.Electricity_bill__c = dElectricityMeterReading;
        cInvoice.Water_bill__c = dWaterMeterReading;
        cInvoice.Gas_bill__c = dGasMeterReading;
        cInvoice.Electricity_meter_reading__c = dElectricityMeterReading;
        cInvoice.Water_meter_reading__c = dWaterMeterReading;
        cInvoice.Gas_meter_reading__c = dGasMeterReading;
        update cInvoice;
        cUser.Debet_Account__c = cUser.Debet_Account__c - cInvoice.Bill_amount__c;
        update cUser;
    }

}