devorg/force-app/main/default/objects/Housing_invoice__c/Housing_invoice__c.object-meta.xml
<CustomObject>
    <label>Housing_invoice</label>
    <nameField>
        <label>Housing_invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devorg/force-app/main/default/objects/Housing_invoice__c/fields/Bill_amount__c.field-meta.xml
<CustomField>
    <fullName>Bill_amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bill amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_invoice__c/fields/Electricity_bill__c.field-meta.xml
<CustomField>
    <fullName>Electricity_bill__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Electricity bill</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_invoice__c/fields/Electricity_meter_reading__c.field-meta.xml
<CustomField>
    <fullName>Electricity_meter_reading__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Electricity_meter_reading</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Housing_invoice__c/fields/Gas_bill__c.field-meta.xml
<CustomField>
    <fullName>Gas_bill__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Gas bill</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_invoice__c/fields/Gas_meter_reading__c.field-meta.xml
<CustomField>
    <fullName>Gas_meter_reading__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Gas_meter_reading</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_invoice__c/fields/Housing_user__c.field-meta.xml
<CustomField>
    <fullName>Housing_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Housing_user</label>
    <referenceTo>Housing_user__c</referenceTo>
    <relationshipLabel>Housing_invoices</relationshipLabel>
    <relationshipName>Housing_invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Housing_invoice__c/fields/Water_bill__c.field-meta.xml
<CustomField>
    <fullName>Water_bill__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Water bill</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Housing_invoice__c/fields/Water_meter_reading__c.field-meta.xml
<CustomField>
    <fullName>Water_meter_reading__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Water_meter_reading</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_payment__c/Housing_payment__c.object-meta.xml
<CustomObject>
    <label>Housing_payment</label>
    <nameField>
        <label>Housing_payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devorg/force-app/main/default/objects/Housing_payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_payment__c/fields/Housing_user__c.field-meta.xml
<CustomField>
    <fullName>Housing_user__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Housing_user</label>
    <referenceTo>Housing_user__c</referenceTo>
    <relationshipLabel>Housing_payments</relationshipLabel>
    <relationshipName>Housing_payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_payment__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Housing_rates__c/Housing_rates__c.object-meta.xml
<CustomObject>
    <label>Housing_rates</label>
    <nameField>
        <label>Housing_rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devorg/force-app/main/default/objects/Housing_rates__c/fields/Electricity_rate__c.field-meta.xml
<CustomField>
    <fullName>Electricity_rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Electricity_rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_rates__c/fields/Gas_rate__c.field-meta.xml
<CustomField>
    <fullName>Gas_rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Gas_rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_rates__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Regon</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

devorg/force-app/main/default/objects/Housing_rates__c/fields/Water_rate__c.field-meta.xml
<CustomField>
    <fullName>Water_rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Water_rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/Housing_user__c.object-meta.xml
<CustomObject>
    <label>Housing_user</label>
    <nameField>
        <label>Housing_user_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing_users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

devorg/force-app/main/default/objects/Housing_user__c/fields/Appartment__c.field-meta.xml
<CustomField>
    <fullName>Appartment__c</fullName>
    <label>Appartment</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Donetsk</fullName>
            </value>
            <value>
                <fullName>Lugansk</fullName>
            </value>
            <value>
                <fullName>Kharkov</fullName>
            </value>
            <value>
                <fullName>Kiev</fullName>
            </value>
            <value>
                <fullName>Rovno</fullName>
            </value>
            <value>
                <fullName>Chernigov</fullName>
            </value>
            <value>
                <fullName>Lvov</fullName>
            </value>
            <value>
                <fullName>Uzhgorod</fullName>
            </value>
            <value>
                <fullName>Ternopol</fullName>
            </value>
            <value>
                <fullName>Odessa</fullName>
            </value>
            <value>
                <fullName>Mariupol</fullName>
            </value>
            <value>
                <fullName>Kherson</fullName>
            </value>
            <value>
                <fullName>Dnepr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Debet_Account__c.field-meta.xml
<CustomField>
    <fullName>Debet_Account__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Debet Account</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/isManager__c.field-meta.xml
<CustomField>
    <fullName>isManager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isManager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Housing_user__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <label>Last_name</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

devorg/force-app/main/default/objects/Housing_user__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

devorg/force-app/main/default/classes/HousingUserController.cls
global with sharing class HousingUserController
{
    private final String szErrMaskStart = 'The error is occured:';
    private final String szErrAffectedFields = 'Affected fields';
    private final String szLoginPage = '/apex/Housing_login';
    private final String szPageManager = '/apex/Housing_manager';
    private final String szErrorPositiveBalance = 'Your account must have a positive balance';
    private final String szErrorInvalidPayment = 'Impossible payment. Check the amount.';
    private final String szErrorTypePayment = 'Payment value must be decimal number.';
    private final String szErrorTypeMeterReadings = 'Meter reading value must be decimal number.';
    private final String szErrorInvalidStreet = 'Street field must contain a street name and building number.';
    private final String szErrorNoRates = 'Rates not found for this region.';
    private final String szErrorCannotPutReadings = 'Unpossible calculate invoice without rates.';
    private final String szErrorNoSupporter = 'Current manager is not found';
    private List<DisplayRates> lRegions;
    private List<DisplayPaymentHistory> lPaymentHistory;
    private String szUserId;
    public Housing_user__c cUser {get; set;}
    public String szElectricity {get; set;}
    public String szWater {get; set;}
    public String szGas {get; set;}
    public String szPayment {get; set;}
    public Boolean bMetersReadingVisible {get; set;}
    public Boolean bChangeAddressVisible {get; set;}
    public Boolean bNewMessageVisible {get; set;}
    public Decimal dUserBalance {get; set;}
    public String szRegion {get;set;}
    public String szCity {get;set;}
    public String szStreet {get; set;}
    public String szAppartment {get; set;}
    public String szMessageBody {get; set;}

    public HousingUserController()
    {
        szUserId = ApexPages.currentPage().getParameters().get('UserId');
    }
    public PageReference init()
    {
        if(String.isBlank(szUserId))
        {
            return redirectToHousingLoginPage();
        }
        cUser = getHousingUser(szUserId);
        bMetersReadingVisible = false;
        bChangeAddressVisible = false;
        dUserBalance = cUser.Debet_Account__c;
        szRegion = cUser.Region__c;
        szCity = cUser.City__c;
        szStreet = cUser.Street__c;
        szAppartment = cUser.Appartment__c;
        return null;
    }
    public PageReference redirectToHousingLoginPage()
    {
        PageReference prReference = new PageReference(szLoginPage);
        prReference.setRedirect(true);
        return prReference;
    }

    public void sendEmailToManager()
    {
        bNewMessageVisible = true;
    }

    public void sendMessage()
    {
        bNewMessageVisible = false;
        Housing_user__c[] lManager = [select Email__c, Region__c from Housing_user__c where Region__c = :cUser.Region__c and isManager__c = true limit 1];
        if(lManager.size() > 0)
        {
            HousingMessager.sendMessage(szMessageBody, 'From '+cUser.First_Name__c+' '+cUser.Last_name__c+' '+cUser.Email__c, cUser.Email__c, lManager[0].Email__c);
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, szErrorNoSupporter));
        }
    }

    public List<DisplayRates> getRates()
    {
        system.debug(cUser);
        Housing_rates__c cRates = new Housing_rates__c();
        lRegions = new List<DisplayRates>();
        try
        {
            cRates = [select Id, Electricity_rate__c, Gas_rate__c, Water_rate__c
                      from Housing_rates__c
                      where Region__c = :cUser.Region__c limit 1];
        }
        catch(QueryException e)
        {
            system.debug(e);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, szErrorNoRates));
            return lRegions;
        }
        DisplayRates rate = new DisplayRates();
        rate.setElectricityRate(cRates.Electricity_rate__c);
        rate.setWaterRate(cRates.Water_rate__c);
        rate.setGasRate(cRates.Gas_rate__c);
        lRegions.add(rate);
        return lRegions;
    }

    public Housing_user__c getHousingUser(String szUserId)
    {
        Housing_user__c[] lUsers = [select Id, Email__c, Debet_Account__c, Region__c, City__c, Street__c, Appartment__c,
                                           First_Name__c, Last_name__c, isManager__c
                                    from Housing_user__c
                                    where Id = :szUserId
                                    limit 1];
        return lUsers[0];
    }

    public PageReference putMeterReadingValues()
    {
        Housing_invoice__c cNewInvoice = new Housing_invoice__c();
        try
        {
            cNewInvoice.Housing_user__c = cUser.Id;
            cNewInvoice.Electricity_meter_reading__c = Decimal.valueOf(szElectricity);
            cNewInvoice.Water_meter_reading__c = Decimal.valueOf(szWater);
            cNewInvoice.Gas_meter_reading__c = Decimal.valueOf(szGas);
        }
        catch(TypeException e)
        {
            system.debug(e);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, szErrorTypeMeterReadings));
            return null;
        }
        bMetersReadingVisible = false;
        if(lRegions.size() > 0)
        {
            dUserBalance = HousingInvoiceCalculation.calculateDebtAmount(cUser,
                    cNewInvoice.Electricity_meter_reading__c,
                    cNewInvoice.Water_meter_reading__c,
                    cNewInvoice.Gas_meter_reading__c,
                    lRegions[0].dDisplayElectricity,
                    lRegions[0].dDisplayWater,
                    lRegions[0].dDisplayGas);
            cNewInvoice.Electricity_bill__c = HousingInvoiceCalculation.calculateElectricityAmount(cNewInvoice.Electricity_meter_reading__c,
                    lRegions[0].dDisplayElectricity);
            cNewInvoice.Water_bill__c = HousingInvoiceCalculation.calculateWaterAmount(cNewInvoice.Water_meter_reading__c,
                    lRegions[0].dDisplayWater);
            cNewInvoice.Gas_bill__c = HousingInvoiceCalculation.calculateGasAmount(cNewInvoice.Gas_meter_reading__c,
                    lRegions[0].dDisplayGas);
            cNewInvoice.Bill_amount__c = cNewInvoice.Electricity_bill__c + cNewInvoice.Water_bill__c + cNewInvoice.Gas_bill__c;
            Database.SaveResult dbResult = Database.insert(cNewInvoice, false);
            if(!dbResult.isSuccess())
            {
                for(Database.Error dbError : dbResult.getErrors())
                {
                    System.debug(szErrMaskStart);
                    System.debug(dbError.getStatusCode() + ': ' + dbError.getMessage());
                    System.debug(szErrAffectedFields + dbError.getFields());
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,dbError.getMessage()));
                }
                return null;
            }
            String szBody = 'Hello, ' + cUser.First_Name__c + '! <br> ';
            szBody += 'Please note that your debt is:';
            szBody += '<br>';
            szBody += 'Electricity: ' + cNewInvoice.Electricity_bill__c + '<br>';
            szBody += 'Water: ' + cNewInvoice.Water_bill__c + '<br>';
            szBody += 'Gas: ' + cNewInvoice.Gas_bill__c + '<br>';
            szBody += '-------------------------------------<br>';
            szBody += 'To pay: ' + cNewInvoice.Bill_amount__c + '<br>';
            szBody += '<br>';
            szBody += 'Please pay it as soon as possible! <br>';
            szBody += 'With kind regards.';
            Housing_user__c cManager = [select Id, Email__c from Housing_user__c where Region__c = :cUser.Region__c AND isManager__c = true limit 1];
            HousingMessager.sendMessage(szBody, 'Invoice', cManager.Email__c, cUser.Email__c);
            return null; // stay on the same page
        }
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,szErrorCannotPutReadings));
        return null;
    }

    public void initMeterReadingValues()
    {
        szElectricity = '0';
        szWater = '0';
        szGas = '0';
        bMetersReadingVisible = true;
        //return null;// stay on the same page
    }

    public PageReference makePayment()
    {
        Housing_payment__c cNewPayment = new Housing_payment__c();
        cNewPayment.Housing_user__c = cUser.Id;
        try
        {
            cNewPayment.Amount__c = Decimal.valueOf(szPayment);
            cUser.Debet_Account__c = HousingInvoiceCalculation.changeUserDebtAfterPayment(cUser.Debet_Account__c, cNewPayment.Amount__c);

            update cUser;
        }
        catch(DmlException e)
        {
            system.debug(e);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, szErrorInvalidPayment));
            return null;
        }
        catch(TypeException e)
        {
            system.debug(e);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, szErrorTypePayment));
            return null;
        }
        catch(HousingPaymentException e)
        {
            system.debug(e);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.szMessage));
            return null;
        }
        dUserBalance = cUser.Debet_Account__c;

        Database.SaveResult dbResult = Database.insert(cNewPayment, false);
        if(!dbResult.isSuccess())
        {
            for(Database.Error dbError : dbResult.getErrors())
            {
                System.debug(szErrMaskStart);
                System.debug(dbError.getStatusCode() + ': ' + dbError.getMessage());
                System.debug(szErrAffectedFields + dbError.getFields());
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,dbError.getMessage()));
            }
            return null;
        }
        szPayment = '';
        return null;// stay on the same page
    }

    public List<DisplayPaymentHistory> getPaymentHistory()
    {
        lPaymentHistory = new List<DisplayPaymentHistory>();
        for(Housing_payment__c item : [select Housing_user__c, Amount__c, Time__c
                                       from Housing_payment__c
                                       where Housing_user__c = :cUser.Id
                                       order by Time__c desc])
        {
            lPaymentHistory.add(new DisplayPaymentHistory(item));
        }
        return lPaymentHistory;
    }

    public PageReference changeAddressStart()
    {
        if(cUser.Debet_Account__c >= 0)
        {
            bChangeAddressVisible = true;
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, szErrorPositiveBalance));
        }
        return null;
    }

    public PageReference changeAddressFinish()
    {
        try
        {
            if(String.isBlank(szStreet))
            {
                throw new HousingEmptyFieldException();
            }
            cUser.Street__c = szStreet.trim();
            cUser.Appartment__c = szAppartment.trim();
            update cUser;
            szRegion = cUser.Region__c;
            szCity = cUser.City__c;
        }
        catch(DmlException e)
        {
            system.debug(e);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, szErrorInvalidStreet));
            return null;
        }
        catch(HousingEmptyFieldException e)
        {
            system.debug(e);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.szMessage));
            return null;
        }
        bChangeAddressVisible = false;
        return null;
    }

    public class DisplayRates
    {
        private Decimal dElecticity;
        private Decimal dWater;
        private Decimal dGas;
        public DisplayRates()
        {
            dElecticity = 0.0;
            dWater = 0.0;
            dGas = 0.0;
        }
        public void setElectricityRate(Decimal dElecticityRate)
        {
            dElecticity = dElecticityRate;
        }
        public void setWaterRate(Decimal dWaterRate)
        {
            dWater = dWaterRate;
        }
        public void setGasRate(Decimal dGasRate)
        {
            dGas = dGasRate;
        }
        // Properties for use in the Visualforce view
        public Decimal dDisplayElectricity
        {
            get { return dElecticity; }
        }
        public Decimal dDisplayWater
        {
            get { return dWater; }
        }
        public Decimal dDisplayGas
        {
            get { return dGas; }
        }
    }
    public class DisplayPaymentHistory
    {
        private Housing_payment__c cPayment;
        public DisplayPaymentHistory(Housing_payment__c cPayment)
        {
            this.cPayment = cPayment;
        }
        // Properties for use in the Visualforce view
        public Decimal dDisplayAmount
        {
            get { return cPayment.Amount__c; }
        }
        public Datetime dtDisplayDateTime
        {
            get { return cPayment.Time__c; }
        }
    }

    public PageReference redirectToManager()
    {
        PageReference prReference = new PageReference(szPageManager);
        prReference.getParameters().put('UserId', cUser.Id);
        prReference.setRedirect(true);
        return prReference;
    }

}